services:
  maildev:
    image: djfarrelly/maildev
    command: bin/maildev --hide-extensions STARTTLS
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      MAILDEV_WEB_PORT: 1080
      MAILDEV_SMTP_PORT: 1025
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
      REDIS_DATABASES: 1
    volumes:
      - cache:/data
    restart: always
volumes:
  cache: