services:
  maildev:
    image: djfarrelly/maildev
    command: bin/maildev --hide-extensions STARTTLS
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      MAILDEV_WEB_PORT: 1080
      MAILDEV_SMTP_PORT: 1025
    restart: always
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: legal_site
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dcagatay/pwless-pgadmin4
    ports:
      - 5050:80
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin: